language: java
jdk:
- oraclejdk8
script: mvn clean package
addons:
  artifacts: true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gG0aUcOBXAi44UvphDH2jPWVKw6yrZgFTtJPbXSTRhJO5l8s3qc339bklPYMnER6YkXL1j5qjr/jPdfbyEOyQP8FxeOMiNwnDXhpQfCmVDlRUTYV2tDKjm5+LpknK5NlTbUMGq8ZIbRlFhUs3Gdc/p/rFQQ6eMcA+X7KERcOusUf+2EeJweGaVoG9o2OMBYHsmtXtQvhjHaZmbG2vAn0FxucFGqZR9pQphIkelQD+0Ff81P08MoHh7zZWFPPOzFH+caLgTyjJjWIkypi3KnGQA6zem94X/wIW9p+POTabGstt8AhLPsAGHDdIP3mYH9tKlSBUlJ+lXIMusCwfnktWiubsfInMXAhISr+2C5IcdP9Z4eh36OQO50rQPo1fxLEk1JsKx3ttLKz0yLIDgwnlOgt1FS7Ldi6Y7M0u9L5f6/mPY0MaoUscd9fk1b1f1RgU4r1H+6zhNrCRMzv9t+wP6mrsQUGXFJylcwvyK4rlHePktRNz2HHAdBTwelb7beouuDIxUxE4DHSfD0kQPIsEeTCs2hE/AKz0zeKGGMAXk2oM+CLxEsaQX7nTftd7PkGRvQxoOGy0/am5qol1WlOSMIVrOyEvOndYC2abeQIB6Gg07UvU3ldHGgXbTM8+svS9EzNjN/rCrF57ufMwCSdO6V11TyWa6LdVUguMzxrLso=
  file: target/*.jar
  on:
    tags: true
